#!/bin/bash
ls -A | awk '{if ($1 == "." || $1 == "..") print $1; else files[NR] = $1;} END {for (i in files) print files[i]}' | sort -f | awk '{if (system("[ -d \""$0"\" ]") == 0) print $0"/"; else print $0}' | tr '\n' ',' | sed 's/,$/\n/'
